version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: face-detect/frontend:1.0.0
    container_name: face-detect-frontend
    ports:
      - "3001:80"
    # environment:
    #   - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: face-detect/backend:1.0.0
    container_name: face-detect-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/face_recognition
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face_recognition
    ports:
      - "5213:5432"
    volumes:
      - ./database/db-data:/var/lib/postgresql/data
